title: Caffeine and Cashflow
description: Support, documentation, security and privacy information for Caffeine and Cashflow apps.
url: https://anthonypaddison.github.io
baseurl: /caffeine-and-cashflow-support
theme: minima
header_pages:
  - support.md
  - security.md
  - timed-highlight.md
  - timed-highlight-privacy.md

